"""
ingestion/chunk.py
------------------
Section-first chunking pipeline (parse_pdf-based architecture).

Flow:
1) Load mapped section seeds from data/processed/raw_sections_ot.jsonl
   (generated by ingestion.extract using ingestion.parse_pdf).
2) Apply semantic chunking WITHIN each section independently.
3) Enforce max token budget per chunk.
4) Add sentence-overlap chunks across adjacent chunks in the same chapter.
5) Run 9 validation tests (including overlap and section-level checks).

This script intentionally does NOT run propositions.py.
"""

from __future__ import annotations

import json
import os
import random
import re
import statistics
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
from dotenv import load_dotenv
from llama_index.core import Document
from llama_index.core.node_parser import SemanticSplitterNodeParser
from llama_index.embeddings.openai import OpenAIEmbedding
from tqdm import tqdm

from config import cfg

load_dotenv()

RAW_SECTIONS_PATH = "data/processed/raw_sections_ot.jsonl"
CHUNKS_PATH = cfg.paths.chunks_ot
MAX_CHUNK_TOKENS = 440
OVERLAP_SENTENCE_COUNT = 2
MIN_CHUNK_CHARS = 40
MIN_CHUNK_TOKENS = 15
MIN_TABLE_TEXT_CHARS = 100
PRONOUN_START_RE = re.compile(r"^(it|they|this|these|its|their)\b", re.IGNORECASE)
SENT_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")


# ---------------------------------------------------------------------------
# Token + sentence helpers
# ---------------------------------------------------------------------------

def _get_token_encoder():
    try:
        import tiktoken
        return tiktoken.get_encoding("cl100k_base")
    except Exception:
        return None


def _token_len(text: str, encoder) -> int:
    if encoder is None:
        return max(1, len(text) // 4)
    return len(encoder.encode(text))


def _split_sentences(text: str) -> list[str]:
    return [s.strip() for s in SENT_SPLIT_RE.split(text.strip()) if s.strip()]


# Clause boundary split (used as a fallback when a single sentence exceeds the
# token budget). Splits on `;`, `:`, `, ` (with following space) so we can
# emit clause-sized fragments rather than slicing mid-token.
_CLAUSE_SPLIT_RE = re.compile(r"(?<=[;:])\s+|(?<=,)\s+(?=[A-Z])")


def _back_off_to_sentence_end(text: str, encoder, max_tokens: int) -> str:
    """
    Return the largest prefix of `text` that fits within `max_tokens` AND
    ends at a sentence terminator. Drops any partial trailing sentence.

    If no sentence terminator fits within budget, returns "" (caller decides
    fallback — this never returns a mid-sentence cut).

    Used for:
      - Overlap chunk body trimming (B.3 fix for the 64% mid-sentence overlap
        truncation found in audit 2026-04-28).
      - Long-sentence guard inside _split_to_token_budget.
    """
    if not text:
        return ""
    if _token_len(text, encoder) <= max_tokens:
        # Whole text fits. Still verify it ends at a sentence terminator;
        # otherwise back off to the last terminator we can find.
        if text.rstrip().endswith((".", "!", "?")):
            return text.strip()
        sents = _split_sentences(text)
        if not sents or not sents[-1].endswith((".", "!", "?")):
            sents = sents[:-1]  # drop incomplete trailing sentence if present
        return " ".join(sents).strip()

    # Greedy accumulate sentences until adding the next would exceed budget.
    sents = _split_sentences(text)
    out: list[str] = []
    for s in sents:
        candidate = " ".join(out + [s])
        if _token_len(candidate, encoder) > max_tokens:
            break
        out.append(s)
    if out:
        return " ".join(out).strip()
    # Single first sentence already exceeds budget. Caller must decide.
    return ""


def _sanitize_section_title(section_title: str, chapter_title: str, section_num: str) -> str:
    """
    Never allow 1-2 char section titles (e.g., 'A', 'B').
    Replace with chapter_title + section_num fallback.
    """
    title = (section_title or "").strip()
    if len(title) <= 2:
        sec = (section_num or "").strip()
        if sec:
            return f"{chapter_title} {sec}".strip()
        return chapter_title
    return title


def _last_n_sentences(text: str, n: int = 2) -> str:
    sents = _split_sentences(text)
    if not sents:
        return ""
    return " ".join(sents[-n:]).strip()


def _split_to_token_budget(text: str, encoder, max_tokens: int) -> list[str]:
    """Split text into <= max_tokens pieces preferring sentence boundaries."""
    if _token_len(text, encoder) <= max_tokens:
        return [text.strip()]

    pieces: list[str] = []
    current: list[str] = []

    for sent in _split_sentences(text):
        # Very long sentence fallback (B.3 fix: split on clause boundaries
        # rather than mid-token). Slicing mid-token previously contributed to
        # the 9.4% mid-sentence chunk-end rate found in the 2026-04-28 audit.
        if _token_len(sent, encoder) > max_tokens:
            if current:
                pieces.append(" ".join(current).strip())
                current = []
            # First try clause-level splits (`;`, `:`, comma+capital). Each
            # resulting fragment is treated like its own sentence for budget
            # accounting; we accumulate them greedily.
            clauses = [c.strip() for c in _CLAUSE_SPLIT_RE.split(sent) if c.strip()]
            local: list[str] = []
            for c in clauses:
                cand = " ".join(local + [c]).strip()
                if local and _token_len(cand, encoder) > max_tokens:
                    pieces.append(" ".join(local).strip())
                    local = [c]
                else:
                    local.append(c)
            if local:
                rem = " ".join(local).strip()
                if _token_len(rem, encoder) > max_tokens:
                    # Single clause still exceeds budget. Drop it rather than
                    # emit a mid-clause cut. This is a rare safety valve —
                    # losing the rare table-row-as-one-sentence is preferable
                    # to publishing a chunk that ends mid-clause.
                    print(
                        f"  [chunker] dropping single clause >{max_tokens} tokens "
                        f"(len={len(rem)} chars): {rem[:80]}…"
                    )
                else:
                    pieces.append(rem)
            continue

        candidate = " ".join(current + [sent]).strip()
        if current and _token_len(candidate, encoder) > max_tokens:
            pieces.append(" ".join(current).strip())
            current = [sent]
        else:
            current.append(sent)

    if current:
        pieces.append(" ".join(current).strip())

    cleaned = []
    for p in pieces:
        if len(p) < MIN_CHUNK_CHARS:
            continue
        if _token_len(p, encoder) < MIN_CHUNK_TOKENS:
            continue
        cleaned.append(p)
    return cleaned


def _is_noise_chunk(text: str) -> bool:
    t = " ".join(text.split()).strip()
    tl = t.lower()
    if not t:
        return True
    if tl in {"review questions", "learning objectives", "chapter review"}:
        return True
    if tl.startswith("learning objectives"):
        return True
    if "review questions" in tl[:120]:
        return True
    if re.fullmatch(r"(figure|table)\s+\d+\.\d+\.?", tl):
        return True
    if re.fullmatch(r"[\d\s.,;:()\-/]+", t):
        return True
    return False


def _table_reject_reason(text: str) -> str:
    """Return empty string if valid table prose, else reject reason."""
    t = " ".join((text or "").split()).strip()
    tl = t.lower()
    if len(t) < MIN_TABLE_TEXT_CHARS:
        return "short_text"
    if re.search(r"\b(figure|table)\s*\d+\.\d+\b", tl):
        return "figure_metadata"
    if "learning objective" in tl:
        return "learning_objectives"
    if "review question" in tl:
        return "review_questions"
    if t.count("|") > 20 and len(t) < 200:
        return "dense_pipes_low_content"
    return ""


def _trim_overlap_to_budget(prefix: str, body: str, encoder, max_tokens: int) -> str:
    """
    Build an overlap chunk that joins `prefix` (last 2 sentences of previous
    chunk) with `body` (current chunk text), capped at `max_tokens` AT A
    SENTENCE BOUNDARY.

    B.3 fix (audit 2026-04-28): the previous implementation truncated the body
    mid-token (`encoder.decode(b_toks[:remain])`) which caused 64% of overlap
    chunks to end mid-sentence. We now back off body to the last sentence
    terminator within the remaining budget; partial trailing sentences are
    dropped, never sliced.
    """
    anchor = "Context from previous chunk:"
    merged = f"{anchor} {prefix} {body}".strip()
    if _token_len(merged, encoder) <= max_tokens:
        return merged

    # If the prefix + anchor alone already exceeds budget, return prefix-only
    # (still aligned to sentence boundaries — _last_n_sentences guarantees that).
    prefix_only = f"{anchor} {prefix}".strip()
    if _token_len(prefix_only, encoder) >= max_tokens:
        return prefix_only

    # Otherwise: back off the body to the largest sentence-aligned prefix that
    # fits within the remaining budget.
    remain = max_tokens - _token_len(prefix_only, encoder)
    body_clipped = _back_off_to_sentence_end(body, encoder, remain)
    if not body_clipped:
        # The first body sentence alone exceeds the remaining budget. Return
        # the prefix-only overlap rather than emit a mid-sentence cut.
        return prefix_only
    return f"{prefix_only} {body_clipped}".strip()


# ---------------------------------------------------------------------------
# Load + semantic split
# ---------------------------------------------------------------------------

def load_raw_sections(path: str = RAW_SECTIONS_PATH) -> list[dict]:
    if not Path(path).exists():
        # Source-specific extraction; this is a temporary inversion that B.7 (pipeline orchestrator)
        # will replace by passing pre-extracted elements into the chunker.
        from ingestion.sources.openstax_anatomy.extract import extract_pdf
        print(f"{path} not found. Running extraction first...")
        extract_pdf(cfg.paths.raw_ot_pdf)

    with open(path, "r", encoding="utf-8") as f:
        rows = [json.loads(line) for line in f if line.strip()]
    return rows


def _build_splitter(threshold: int) -> SemanticSplitterNodeParser:
    api_key = os.environ.get("OPENAI_API_KEY")
    embed_model = OpenAIEmbedding(
        model="text-embedding-3-small",
        api_key=api_key,
        embed_batch_size=100,
    )
    return SemanticSplitterNodeParser(
        embed_model=embed_model,
        breakpoint_percentile_threshold=threshold,
        buffer_size=1,
    )


def semantic_chunk_sections(
    section_rows: list[dict],
    threshold: int = 90,
    max_chunk_tokens: int = MAX_CHUNK_TOKENS,
) -> list[dict]:
    """Semantic split each section independently."""
    splitter = _build_splitter(threshold)
    encoder = _get_token_encoder()

    base_chunks: list[dict] = []
    seq = 0

    for sec in tqdm(section_rows, desc="Semantic splitting sections"):
        text = (sec.get("text") or "").strip()
        if len(text) < MIN_CHUNK_CHARS:
            continue

        doc = Document(text=text)
        try:
            nodes = splitter.get_nodes_from_documents([doc], show_progress=False)
            node_texts = [(n.text or "").strip() for n in nodes if (n.text or "").strip()]
        except Exception as exc:
            print(f"Splitter fallback on section {sec.get('source_section_id')} due to: {exc}")
            node_texts = [text]

        for node_text in node_texts:
            parts = _split_to_token_budget(node_text, encoder, max_tokens=max_chunk_tokens)
            if not parts:
                continue

            for part in parts:
                seq += 1
                chunk_obj = {
                    "chunk_id": str(uuid.uuid4()),
                    "text": part,
                    "chapter_num": sec["chapter_num"],
                    "chapter_title": sec["chapter_title"],
                    "section_num": sec.get("section_num", ""),
                    "section_title": _sanitize_section_title(
                        sec.get("section_title", ""),
                        chapter_title=sec.get("chapter_title", ""),
                        section_num=sec.get("section_num", ""),
                    ),
                    "subsection_title": sec.get("subsection_title", ""),
                    "page": sec["page"],
                    "element_type": "paragraph",
                    "is_overlap": False,
                    "domain": sec["domain"],
                    "source_section_id": sec.get("source_section_id", ""),
                    "source_level": sec.get("source_level", 1),
                    "sequence_index": seq,
                }
                if _is_noise_chunk(chunk_obj["text"]):
                    continue
                if _token_len(chunk_obj["text"], encoder) < MIN_CHUNK_TOKENS:
                    continue
                base_chunks.append(chunk_obj)

    return base_chunks


def add_overlap_chunks(
    base_chunks: list[dict],
    overlap_sentences: int = OVERLAP_SENTENCE_COUNT,
    max_chunk_tokens: int = MAX_CHUNK_TOKENS,
) -> list[dict]:
    """
    Add overlap chunks: prepend last N sentences from previous chunk to current,
    only within same chapter.
    """
    encoder = _get_token_encoder()
    ordered = sorted(base_chunks, key=lambda c: c.get("sequence_index", 0))

    overlaps: list[dict] = []
    for i in range(1, len(ordered)):
        prev = ordered[i - 1]
        curr = ordered[i]

        if prev["chapter_num"] != curr["chapter_num"]:
            continue

        prefix = _last_n_sentences(prev["text"], overlap_sentences)
        if not prefix:
            continue

        overlap_text = _trim_overlap_to_budget(prefix, curr["text"], encoder, max_chunk_tokens)
        if _is_noise_chunk(overlap_text):
            continue
        if _token_len(overlap_text, encoder) < MIN_CHUNK_TOKENS:
            continue

        overlaps.append({
            **curr,
            "chunk_id": str(uuid.uuid4()),
            "text": overlap_text,
            "element_type": "paragraph_overlap",
            "is_overlap": True,
            "original_chunk_id": curr["chunk_id"],
            "overlap_source_chunk_id": prev["chunk_id"],
            "overlap_prefix": prefix,
            "sequence_index": curr.get("sequence_index", 0) + 0.1,
        })

    return ordered + overlaps


def merge_pronoun_start_chunks(
    base_chunks: list[dict],
    max_chunk_tokens: int = MAX_CHUNK_TOKENS,
) -> tuple[list[dict], int]:
    """
    Merge pronoun-start paragraph chunks into previous paragraph chunk
    within same chapter+section when token budget allows.
    """
    encoder = _get_token_encoder()
    ordered = sorted(base_chunks, key=lambda c: c.get("sequence_index", 0))
    merged: list[dict] = []
    merge_count = 0

    for c in ordered:
        text = c["text"].strip()
        if (
            merged
            and c.get("element_type") == "paragraph"
            and merged[-1].get("element_type") == "paragraph"
            and c.get("chapter_num") == merged[-1].get("chapter_num")
            and c.get("section_num") == merged[-1].get("section_num")
            and PRONOUN_START_RE.match(text)
        ):
            combo = f"{merged[-1]['text'].rstrip()} {text}".strip()
            if _token_len(combo, encoder) <= max_chunk_tokens:
                merged[-1]["text"] = combo
                merge_count += 1
                continue

        merged.append(c)

    return merged, merge_count


def _build_page_section_lookup(section_rows: list[dict]) -> dict[int, dict]:
    """
    Map page -> best matching section metadata.
    Preference:
      1) higher source_level (L2 over L1)
      2) smaller page span (more specific section range)
    """
    lookup: dict[int, dict] = {}
    for s in section_rows:
        start = int(s.get("page", 0))
        end = int(s.get("page_end", start))
        if start <= 0:
            continue
        if end < start:
            end = start

        level = int(s.get("source_level", 1))
        span = end - start + 1
        for p in range(start, end + 1):
            cur = lookup.get(p)
            if cur is None:
                lookup[p] = {**s, "_span": span, "_level": level}
                continue
            if (level > cur["_level"]) or (level == cur["_level"] and span < cur["_span"]):
                lookup[p] = {**s, "_span": span, "_level": level}
    return lookup


def _convert_table_to_text(raw_table: str, client, model: str, prompt_template: str) -> str:
    """Convert a raw table string to prose using Claude with retries."""
    prompt = prompt_template.format(table_text=raw_table)
    for attempt in range(3):
        try:
            msg = client.messages.create(
                model=model,
                max_tokens=900,
                messages=[{"role": "user", "content": prompt}],
            )
            return msg.content[0].text.strip()
        except Exception:
            time.sleep(1.5 * (attempt + 1))
    return ""


def extract_table_chunks(
    pdf_path: str,
    section_rows: list[dict],
) -> tuple[list[dict], dict]:
    """
    Extract tables from PDF, convert to prose, map to section metadata,
    and return ChunkSchema-like table chunks.
    """
    import anthropic
    import pdfplumber

    page_meta = _build_page_section_lookup(section_rows)
    client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
    model = cfg.models.propositions
    prompt_template = cfg.prompts.table_to_text

    table_chunks: list[dict] = []
    total_tables = 0
    filtered_raw = 0
    filtered_converted = 0

    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            tables = page.extract_tables() or []
            total_tables += len(tables)

            for table in tables:
                rows = []
                for row in table or []:
                    cells = [(c or "").replace("\n", " ").strip() for c in row]
                    if any(cells):
                        rows.append(" | ".join(cells))
                raw = "\n".join(rows).strip()
                if not raw:
                    continue

                if _table_reject_reason(raw):
                    filtered_raw += 1
                    continue

                converted = _convert_table_to_text(raw, client, model, prompt_template)
                if not converted:
                    filtered_converted += 1
                    continue

                if _table_reject_reason(converted):
                    filtered_converted += 1
                    continue

                meta = page_meta.get(page_num)
                if meta is None:
                    # fallback metadata when page is not covered by sections
                    chapter_num = 0
                    chapter_title = "Unknown"
                    section_num = ""
                    section_title = "Unknown"
                    subsection_title = ""
                    source_section_id = ""
                    source_level = 1
                else:
                    chapter_num = int(meta.get("chapter_num", 0))
                    chapter_title = meta.get("chapter_title", "")
                    section_num = meta.get("section_num", "") or ""
                    section_title = _sanitize_section_title(
                        meta.get("section_title", ""),
                        chapter_title=chapter_title,
                        section_num=section_num,
                    )
                    subsection_title = meta.get("subsection_title", "")
                    source_section_id = meta.get("source_section_id", "")
                    source_level = int(meta.get("source_level", 1))

                table_chunks.append({
                    "chunk_id": str(uuid.uuid4()),
                    "text": " ".join(converted.split()).strip(),
                    "chapter_num": chapter_num,
                    "chapter_title": chapter_title,
                    "section_num": section_num,
                    "section_title": section_title,
                    "subsection_title": subsection_title,
                    "page": page_num,
                    "element_type": "table",
                    "is_overlap": False,
                    "domain": "ot",
                    "source_section_id": source_section_id,
                    "source_level": source_level,
                    "sequence_index": 10_000_000 + len(table_chunks),
                })

                # light rate-limit pacing
                time.sleep(0.15)

    stats = {
        "total_tables_in_pdf": total_tables,
        "filtered_raw": filtered_raw,
        "filtered_converted": filtered_converted,
        "table_chunks_added": len(table_chunks),
    }
    return table_chunks, stats


def normalize_chunk_fields(chunks: list[dict]) -> list[dict]:
    """Backfill required normalized fields across all chunk types."""
    normalized = []
    for c in chunks:
        c2 = dict(c)
        c2["is_overlap"] = bool(c2.get("element_type") == "paragraph_overlap")
        c2["section_title"] = _sanitize_section_title(
            c2.get("section_title", ""),
            chapter_title=c2.get("chapter_title", ""),
            section_num=c2.get("section_num", ""),
        )
        normalized.append(c2)
    return normalized


def save_chunks(chunks: list[dict], out_path: str = CHUNKS_PATH) -> None:
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for c in chunks:
            f.write(json.dumps(c, ensure_ascii=False) + "\n")
    print(f"Saved {len(chunks)} chunks -> {out_path}")


# ---------------------------------------------------------------------------
# Validation tests
# ---------------------------------------------------------------------------

@dataclass
class TestResult:
    name: str
    passed: bool
    details: str


def _test_1_token_distribution(chunks: list[dict]) -> TestResult:
    encoder = _get_token_encoder()
    lens = [_token_len(c["text"], encoder) for c in chunks]

    p50 = int(np.percentile(lens, 50))
    p90 = int(np.percentile(lens, 90))
    p95 = int(np.percentile(lens, 95))
    p99 = int(np.percentile(lens, 99))
    mx = max(lens)
    mean = round(float(np.mean(lens)), 2)
    under15 = sum(x < 15 for x in lens)
    over450 = sum(x > 450 for x in lens)

    passed = (p99 < 450 and mx < 512)
    details = (
        f"total={len(chunks)} mean={mean} p50={p50} p90={p90} p95={p95} "
        f"p99={p99} max={mx} under15={under15} over450={over450}"
    )
    return TestResult("TEST 1 — Token distribution", passed, details)


def _estimate_distinct_topics(text: str) -> int:
    sents = _split_sentences(text)
    if len(sents) <= 1:
        return 1
    if len(sents) <= 4:
        return 1

    stop = {
        "the", "and", "for", "that", "with", "from", "this", "these", "those",
        "are", "was", "were", "have", "has", "had", "into", "onto", "over",
        "under", "within", "without", "when", "where", "which", "while", "about",
    }

    def kws(s: str) -> set[str]:
        words = re.findall(r"[A-Za-z][A-Za-z\-]+", s.lower())
        return {w for w in words if len(w) > 3 and w not in stop}

    shifts = 0
    marker_re = re.compile(r"^(however|in contrast|whereas|meanwhile|on the other hand|additionally|in addition|another)\b", re.I)
    prev = kws(sents[0])
    for s in sents[1:]:
        cur = kws(s)
        if not prev and not cur:
            sim = 1.0
        else:
            sim = len(prev & cur) / max(1, len(prev | cur))
        if sim < 0.03 and marker_re.search(s.strip()):
            shifts += 1
        prev = cur

    return 1 + shifts


def _test_2_topic_coherence(chunks: list[dict]) -> tuple[TestResult, list[dict]]:
    paras = [c for c in chunks if c["element_type"] == "paragraph"]
    sample = random.sample(paras, min(10, len(paras)))

    rows = []
    good = 0
    encoder = _get_token_encoder()
    for c in sample:
        distinct = _estimate_distinct_topics(c["text"])
        flag = "GOOD" if distinct == 1 else "BAD"
        if flag == "GOOD":
            good += 1
        rows.append({
            "chunk_id": c["chunk_id"],
            "token_count": _token_len(c["text"], encoder),
            "distinct_topics": distinct,
            "flag": flag,
            "section_title": c.get("section_title", ""),
            "text": c["text"],
        })

    passed = good >= 8
    details = f"GOOD={good}/10 BAD={10-good}/10"
    return TestResult("TEST 2 — Topic coherence", passed, details), rows


def _test_3_pronoun_starts(chunks: list[dict]) -> TestResult:
    p = [c for c in chunks if PRONOUN_START_RE.match(c["text"].strip())]
    pct = (len(p) / len(chunks) * 100.0) if chunks else 0.0
    passed = pct < 5.0
    details = f"count={len(p)} pct={pct:.2f}%"
    return TestResult("TEST 3 — Pronoun-start chunks", passed, details)


def _test_4_noise_detection(chunks: list[dict]) -> TestResult:
    noise = []
    for c in chunks:
        t = " ".join(c["text"].split()).strip()
        tl = t.lower()
        if tl in {"review questions", "learning objectives", "chapter review"}:
            noise.append(c)
            continue
        if re.fullmatch(r"(figure|table)\s+\d+\.\d+\.?", tl):
            noise.append(c)
            continue
        if re.fullmatch(r"[\d\s.,;:()\-/]+", t):
            noise.append(c)
            continue

    passed = len(noise) == 0
    details = f"noise_chunks={len(noise)}"
    return TestResult("TEST 4 — Noise detection", passed, details)


def _test_5_chapter_coverage(chunks: list[dict]) -> tuple[TestResult, dict[int, int]]:
    counts = {ch: 0 for ch in range(1, 29)}
    for c in chunks:
        ch = int(c.get("chapter_num", 0))
        if 1 <= ch <= 28:
            counts[ch] += 1

    missing = [ch for ch, n in counts.items() if n == 0]
    passed = len(missing) == 0
    details = f"missing={missing if missing else 'none'}"
    return TestResult("TEST 5 — Chapter coverage", passed, details), counts


def _test_6_critical_content(chunks: list[dict]) -> tuple[TestResult, dict[str, int]]:
    checks = {
        "axillary nerve": 3,
        "deltoid": 5,
        "rotator cuff": 2,
        "biceps": 3,
    }
    counts = {k: sum(1 for c in chunks if k in c["text"].lower()) for k in checks}
    passed = all(counts[k] > checks[k] for k in checks)
    details = " ".join([f"{k}={v}" for k, v in counts.items()])
    return TestResult("TEST 6 — Critical content check", passed, details), counts


def _extract_props_preview(chunk_text: str) -> list[str]:
    import anthropic

    client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
    prompt = cfg.prompts.proposition_extraction.format(chunk_text=chunk_text)

    msg = client.messages.create(
        model=cfg.models.propositions,
        max_tokens=700,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = msg.content[0].text.strip()
    lines = [ln.strip("-•* \t") for ln in raw.splitlines() if ln.strip()]
    return lines


def _test_7_proposition_preview(chunks: list[dict]) -> tuple[TestResult, dict]:
    # a) one muscle chunk
    muscle = next((c for c in chunks if c["element_type"] == "paragraph" and any(k in c["text"].lower() for k in ["deltoid", "biceps", "rotator cuff"])), None)

    # b) table-converted chunk if available (new parse_pdf flow may not have these)
    table_chunk = next((c for c in chunks if c.get("element_type") == "table"), None)

    # c) clinical concept chunk
    clinical = next((c for c in chunks if any(k in c["text"].lower() for k in ["injur", "disease", "syndrome", "damage", "sprain", "clinical"])), None)

    # fallback for b) if no table chunks exist in this architecture
    if table_chunk is None:
        table_chunk = next((c for c in chunks if c["element_type"] == "paragraph_overlap"), None)

    samples = {
        "a_muscle": muscle,
        "b_table_or_overlap": table_chunk,
        "c_clinical": clinical,
    }

    previews = {}
    ok = True
    for key, c in samples.items():
        if c is None:
            previews[key] = {"error": "No suitable chunk found"}
            ok = False
            continue
        props = _extract_props_preview(c["text"])
        previews[key] = {
            "chunk_id": c["chunk_id"],
            "element_type": c["element_type"],
            "text": c["text"],
            "propositions": props,
        }

    return TestResult("TEST 7 — Proposition preview", ok, "generated previews for 3 chunk types"), previews


def _test_8_overlap_check(chunks: list[dict]) -> TestResult:
    overlaps = [c for c in chunks if c.get("element_type") == "paragraph_overlap"]
    base = {c["chunk_id"]: c for c in chunks if c.get("element_type") == "paragraph"}

    valid_original = 0
    valid_prefix = 0

    for c in overlaps:
        oid = c.get("original_chunk_id")
        sid = c.get("overlap_source_chunk_id")
        prefix = c.get("overlap_prefix", "")

        if oid in base:
            valid_original += 1
        if sid in base and prefix and prefix in base[sid]["text"]:
            valid_prefix += 1

    passed = (len(overlaps) > 0 and valid_original == len(overlaps) and valid_prefix == len(overlaps))
    details = (
        f"overlap_count={len(overlaps)} "
        f"valid_original_chunk_id={valid_original}/{len(overlaps)} "
        f"prefix_in_source={valid_prefix}/{len(overlaps)}"
    )
    return TestResult("TEST 8 — Overlap chunk check", passed, details)


def _test_9_section_level(chunks: list[dict], sections: list[dict]) -> tuple[TestResult, dict]:
    l1 = sum(1 for s in sections if int(s.get("source_level", 1)) == 1)
    l2 = sum(1 for s in sections if int(s.get("source_level", 1)) == 2)

    ax_chunks = [c for c in chunks if "axillary nerve" in c["text"].lower()]
    titles = sorted({c.get("section_title", "") for c in ax_chunks})

    passed = len(ax_chunks) > 3
    details = f"L1={l1} L2={l2} axillary_nerve_chunks={len(ax_chunks)}"
    payload = {"l1": l1, "l2": l2, "axillary_titles": titles}
    return TestResult("TEST 9 — Section-level check", passed, details), payload


def run_all_tests(chunks: list[dict], sections: list[dict]) -> dict:
    results: list[TestResult] = []

    t1 = _test_1_token_distribution(chunks)
    results.append(t1)

    t2, t2_rows = _test_2_topic_coherence(chunks)
    results.append(t2)

    t3 = _test_3_pronoun_starts(chunks)
    results.append(t3)

    t4 = _test_4_noise_detection(chunks)
    results.append(t4)

    t5, chapter_counts = _test_5_chapter_coverage(chunks)
    results.append(t5)

    t6, keyword_counts = _test_6_critical_content(chunks)
    results.append(t6)

    t7, previews = _test_7_proposition_preview(chunks)
    results.append(t7)

    t8 = _test_8_overlap_check(chunks)
    results.append(t8)

    t9, t9_payload = _test_9_section_level(chunks, sections)
    results.append(t9)

    all_pass = all(r.passed for r in results)

    return {
        "all_pass": all_pass,
        "results": results,
        "topic_rows": t2_rows,
        "chapter_counts": chapter_counts,
        "keyword_counts": keyword_counts,
        "previews": previews,
        "section_payload": t9_payload,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(threshold: int = 90, out_path: str = CHUNKS_PATH, run_tests: bool = True) -> int:
    sections = load_raw_sections(RAW_SECTIONS_PATH)
    print(f"Loaded section seeds: {len(sections)} from {RAW_SECTIONS_PATH}")

    base_chunks = semantic_chunk_sections(
        sections,
        threshold=threshold,
        max_chunk_tokens=MAX_CHUNK_TOKENS,
    )
    print(f"Base semantic chunks: {len(base_chunks)}")

    base_chunks, merged_count = merge_pronoun_start_chunks(
        base_chunks,
        max_chunk_tokens=MAX_CHUNK_TOKENS,
    )
    print(f"Base chunks after pronoun-merge: {len(base_chunks)} (merged={merged_count})")

    all_chunks = add_overlap_chunks(
        base_chunks,
        overlap_sentences=OVERLAP_SENTENCE_COUNT,
        max_chunk_tokens=MAX_CHUNK_TOKENS,
    )
    print(f"Total chunks after overlap: {len(all_chunks)}")

    # Parallel table extraction branch (no overlap for table chunks)
    table_chunks, table_stats = extract_table_chunks(
        pdf_path=cfg.paths.raw_ot_pdf,
        section_rows=sections,
    )
    print(
        "Table extraction:",
        f"total_in_pdf={table_stats['total_tables_in_pdf']}",
        f"filtered_raw={table_stats['filtered_raw']}",
        f"filtered_converted={table_stats['filtered_converted']}",
        f"added={table_stats['table_chunks_added']}",
    )

    all_chunks = normalize_chunk_fields(all_chunks + table_chunks)
    print(f"Total chunks after tables + normalization: {len(all_chunks)}")

    save_chunks(all_chunks, out_path)

    if not run_tests:
        return 0

    report = run_all_tests(all_chunks, sections)

    print("\n" + "=" * 70)
    print("VALIDATION TEST RESULTS")
    print("=" * 70)
    for r in report["results"]:
        status = "PASS" if r.passed else "FAIL"
        print(f"[{status}] {r.name}: {r.details}")

    print("\nTEST 2 — Topic coherence sample (10 chunks)")
    for i, row in enumerate(report["topic_rows"], 1):
        print(f"\n[{i}] {row['flag']} topics={row['distinct_topics']} tokens={row['token_count']} section={row['section_title'][:80]}")
        print(row["text"])

    print("\nTEST 5 — Chapter counts")
    for ch in range(1, 29):
        print(f"Ch{ch:02d}: {report['chapter_counts'][ch]}")

    print("\nTEST 6 — Keyword counts")
    for k, v in report["keyword_counts"].items():
        print(f"{k}: {v}")

    print("\nTEST 7 — Proposition preview")
    for key, payload in report["previews"].items():
        print(f"\n{key}:")
        if "error" in payload:
            print(f"  error: {payload['error']}")
            continue
        print(f"  chunk_id: {payload['chunk_id']}")
        print(f"  element_type: {payload['element_type']}")
        print(f"  text: {payload['text'][:600]}")
        print("  propositions:")
        for p in payload.get("propositions", [])[:12]:
            print(f"    - {p}")

    print("\nTEST 9 — Section-level details")
    print(f"L1 sections: {report['section_payload']['l1']}")
    print(f"L2 sections: {report['section_payload']['l2']}")
    print("Section titles with 'axillary nerve' chunks:")
    for t in report["section_payload"]["axillary_titles"]:
        print(f"- {t}")

    print("\nOverall:", "PASS" if report["all_pass"] else "FAIL")
    return 0 if report["all_pass"] else 1


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Section-first semantic chunking with overlap")
    parser.add_argument("--threshold", type=int, default=90)
    parser.add_argument("--output", type=str, default=CHUNKS_PATH)
    parser.add_argument("--no-tests", action="store_true")
    args = parser.parse_args()

    raise SystemExit(main(threshold=args.threshold, out_path=args.output, run_tests=not args.no_tests))
