"""
conversation/state.py
---------------------
Defines TutorState — the single shared object that flows through every
node in the LangGraph graph.

Every field is described inline. Nodes read from state and return
partial updates (LangGraph merges them automatically).

One topic per session. A new session (new thread_id) handles the next topic.
Memory continuity across sessions is handled by mem0 (persistent_memory.py).

Use initial_state() to create a properly initialized state at session start.
"""

from typing import TypedDict, Literal, Optional


class TutorState(TypedDict):
    # --- Identity ---
    student_id: str

    # --- Phase ---
    phase: Literal["rapport", "tutoring", "assessment", "memory_update"]

    # --- Conversation history ---
    # Full list of messages. Oldest turns are replaced by a summary paragraph
    # once turn_count exceeds cfg.session.max_turns.
    messages: list[dict]            # {"role": "tutor"|"student", "content": str}

    # --- Retrieval ---
    # Top-5 chunks returned by the last retriever call.
    # Each dict: {text, chapter_title, section_title, subsection_title, page, score}
    retrieved_chunks: list[dict]

    # --- Answer management ---
    # Extracted by Dean from the top retrieved chunk on the first specific student question.
    # Never shown to Teacher. Immutable once set for this topic.
    # Empty string means not yet locked.
    locked_answer: str

    # --- Hint tracking ---
    hint_level: int                 # current level, starts at 1
    max_hints: int                  # from cfg.session.max_hints

    # --- Turn tracking ---
    turn_count: int
    max_turns: int                  # from cfg.session.max_turns

    # --- Progress ---
    student_reached_answer: bool

    # --- Memory ---
    # Seeded from mem0 at session start. Used during rapport to suggest topic.
    weak_topics: list[dict]         # [{topic: str, difficulty: str, failure_count: int}]

    # --- Dean retry counter ---
    # Resets to 0 on each new student turn.
    # If it reaches cfg.dean.max_teacher_retries, Dean responds directly.
    dean_retry_count: int

    # --- Dean's critique for Teacher retry ---
    # Set by Dean when it rejects a Teacher response. Empty string on first attempt.
    dean_critique: str

    # --- Student state (SocraticLM) ---
    # Dean classifies the student's last message each turn.
    # Passed to Teacher to determine response behavior.
    # None until first student message is classified.
    student_state: Optional[Literal["correct", "incorrect", "question", "irrelevant", "low_effort"]]

    # --- Help abuse tracking (Khanmigo) ---
    # Counts consecutive low-effort student turns.
    # Resets to 0 when student makes a real attempt.
    # When it reaches cfg.dean.help_abuse_threshold, hint_level advances anyway and counter resets.
    # Gated entirely in Python (dean.py) — not LLM logic.
    help_abuse_count: int

    # --- Guiding question chain (SocraticLM) ---
    # Generated by Dean when it first locks the answer for a topic.
    # 3-item list, one question per hint level, derived from retrieved_chunks.
    # Teacher follows this chain in order rather than inventing questions freely.
    # None until Dean generates it on first lock.
    guiding_question_chain: Optional[list[str]]

    # --- Multimodal ---
    is_multimodal: bool
    image_structures: list[str]     # structure names from GPT-4o Vision


def initial_state(student_id: str, cfg) -> TutorState:
    """
    Return a fully initialized TutorState for a new session.
    Call this at the start of every session before invoking the graph.

    Args:
        student_id: Unique identifier for the student.
        cfg:        Loaded config object (from config.py).
    """
    return TutorState(
        student_id=student_id,
        phase="rapport",
        messages=[],
        retrieved_chunks=[],
        locked_answer="",
        hint_level=1,
        max_hints=cfg.session.max_hints,
        turn_count=0,
        max_turns=cfg.session.max_turns,
        student_reached_answer=False,
        weak_topics=[],
        dean_retry_count=0,
        dean_critique="",
        student_state=None,
        help_abuse_count=0,
        guiding_question_chain=None,
        is_multimodal=False,
        image_structures=[],
    )
